version: '3.8'

services:
  anonymity-app:
    build: .
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped 